spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/example_caching_with_redis
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cache:
    type: redis

  redis:
    host: localhost
    port: 6379
